package accessrequest

// Problem type URIs returned by the Access Request Endpoint and Task Status
// Endpoint. Error responses carrying one of these types MUST use the
// application/problem+json media type defined by RFC 9457 and place the URI in
// the problem object's "type" member.
//
// These URNs use the urn:openid:authzen: namespace administered by the OpenID
// Foundation, an intentional profile convention distinct from the
// urn:ietf:params:authzen: sub-namespace used by the base Authorization API.
//
// AuthZEN Access Request and Approval Profile, Section 14 (Error Responses).
// https://openid.github.io/authzen/authzen-access-request-approval-profile-1_0.html#section-14
const (
	// ProblemNotRequestable (HTTP 400): the submitted denial is not requestable.
	ProblemNotRequestable = "urn:openid:authzen:access-request:error:not_requestable"
	// ProblemExpiredDenial (HTTP 410): the requestable denial has expired; the
	// freshness deadline (the earlier of denial.expires_at and any binding_token
	// exp) has passed.
	ProblemExpiredDenial = "urn:openid:authzen:access-request:error:expired_denial"
	// ProblemInvalidDenialBinding (HTTP 400): the submission cannot be bound to
	// the denied AuthZEN Decision.
	ProblemInvalidDenialBinding = "urn:openid:authzen:access-request:error:invalid_denial_binding"
	// ProblemDuplicateRequest (HTTP 409): the Idempotency-Key was reused by the
	// same requester with a materially different submission body.
	ProblemDuplicateRequest = "urn:openid:authzen:access-request:error:duplicate_request"
	// ProblemUnknownTask (HTTP 404): the task handle is unknown or unavailable to
	// the caller.
	ProblemUnknownTask = "urn:openid:authzen:access-request:error:unknown_task"
	// ProblemTaskExpired (HTTP 410): the task handle has expired.
	ProblemTaskExpired = "urn:openid:authzen:access-request:error:task_expired"
	// ProblemInvalidTaskState (HTTP 409): the requested operation cannot be
	// performed in the current task state (for example, cancelling a task that
	// has already reached a terminal status).
	ProblemInvalidTaskState = "urn:openid:authzen:access-request:error:invalid_task_state"
)

// Metadata parameter names this profile registers in the AuthZEN Policy
// Decision Point Metadata Registry.
//
// AuthZEN Access Request and Approval Profile, Section 23.1.
// https://openid.github.io/authzen/authzen-access-request-approval-profile-1_0.html#section-23.1
const (
	// MetadataAccessRequestEndpoint is the access_request_endpoint metadata key:
	// the HTTPS endpoint used to submit Access Requests for requestable denials.
	MetadataAccessRequestEndpoint = "access_request_endpoint"
	// MetadataJWKSURI is the jwks_uri metadata key: the HTTPS URI of the JWK Set
	// holding verification keys for PDP-issued binding_token values and
	// Access-Request-Service-signed approval.state values.
	MetadataJWKSURI = "jwks_uri"
)

// Problem is an RFC 9457 problem-details object specialized for this profile's
// error responses. It is encoded with the application/problem+json media type.
//
// AuthZEN Access Request and Approval Profile, Section 14, and RFC 9457.
// https://www.rfc-editor.org/rfc/rfc9457
type Problem struct {
	// Type is the problem type URI; one of the Problem* constants for the errors
	// this profile defines. REQUIRED for the defined problem types.
	Type string `json:"type"`
	// Title is a short, human-readable summary of the problem type. OPTIONAL.
	Title string `json:"title,omitempty"`
	// Status is the HTTP status code generated by the origin server. OPTIONAL.
	Status int `json:"status,omitempty"`
	// Detail is a human-readable explanation specific to this occurrence.
	// OPTIONAL.
	Detail string `json:"detail,omitempty"`
	// Instance is a URI identifying the specific occurrence. OPTIONAL.
	Instance string `json:"instance,omitempty"`
}

// Error implements the error interface so a Problem can be returned and matched
// as an error value.
//
// AuthZEN Access Request and Approval Profile, Section 14.
// https://openid.github.io/authzen/authzen-access-request-approval-profile-1_0.html#section-14
func (p *Problem) Error() string {
	if p.Detail != "" {
		return "accessrequest: " + p.Type + ": " + p.Detail
	}
	return "accessrequest: " + p.Type
}
